server {
    listen __APP_PORT__;

    root /var/www/dbbackup;
    index back-up.php;

    location / {
        try_files $uri $uri/ /back-up.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:__PHP_SOCK__;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ \.php-config$ { deny all; }
    location ~ /\.ht { deny all; }

    error_log /var/log/nginx/dbbackup_error.log;
    access_log /var/log/nginx/dbbackup_access.log;
}
